# Generated by Django 5.1.2 on 2024-12-18 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('autoparts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'انتظار مراجعة البائع'), ('ACCEPTED', 'قيد التوصيل'), ('DELIVERED', 'تم التوصيل'), ('DENIED', 'رفض')], default='PENDING', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profilecustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoparts.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profileseller')),
            ],
        ),
    ]
